import { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { createUserMessage } from '@deepseek-ai/dsh-llm'
import { scopeTarget } from '@deepseek-ai/dsh-scope'
import { describe, expect, it, vi } from 'vitest'
import type { AccountModelDescriptor } from '../src/account-model-catalog.ts'
import { installAutoModelRouting } from '../src/auto-model-host.ts'
import {
  GITHUB_COPILOT_AUTO_MODEL_ID as AUTO, GITHUB_COPILOT_PREVIEW_PROVIDER_ID as PREVIEW,
} from '../src/copilot-identity.ts'

function model(id: string, contextWindow: number, effort: string): AccountModelDescriptor {
  return {
    id,
    name: id,
    api: 'openai-responses',
    contextWindow,
    maxTokens: Math.floor(contextWindow / 4),
    input: ['text'],
    reasoning: { advertisedEfforts: [effort], unmappedEfforts: [] },
    evidence: {
      endpoints: ['/responses'],
      unsupportedEndpointCount: 0,
      selectedEndpoint: '/responses',
      apiSource: 'advertised-native',
      policySource: 'server-enabled',
      contextWindowSource: 'max_context_window_tokens',
    },
  }
}

function message(text: string) {
  return createUserMessage({ content: [{ type: 'text', text }], source: { kind: 'user' } })
}

describe('Auto model Host integration', () => {
  it('resolves after downstream model selection and freezes one decision per turn', async () => {
    const ctx = new Context()
    const append = vi.fn()
    const agent = { ctx, session: { append, requestHeader: () => undefined } } as unknown as Agent
    const scope = scopeTarget(agent, agent)
    const loadModels = vi.fn(async () => [
      model('fixture-fast', 64_000, 'low'),
      model('fixture-strong', 256_000, 'high'),
    ])
    const dispose = installAutoModelRouting(ctx, { loadModels })
    ctx.emit(scope, 'agent/created', { agent })
    ctx.on('agent/request', async (_payload, next) => ({ ...await next(), provider: PREVIEW, model: AUTO }))
    const signal = new AbortController().signal
    const enter = async (turn: number, text: string) => {
      const messages = [message(text)]
      return ctx.waterfall(scope, 'agent/pre-step', { agent, messages, turn, step: 1, signal },
        async () => ({ kind: 'enter' as const, messages }))
    }
    const request = (turn: number, step = 1) => ctx.waterfall(scope, 'agent/request',
      { agent, turn, step, signal }, async () => ({ provider: 'fixture-seed', model: 'fixture-seed' }))
    try {
      await enter(1, 'Explain this symbol.')
      await expect(request(1)).resolves.toMatchObject({ provider: PREVIEW, model: 'fixture-fast' })
      await enter(1, 'detail '.repeat(1_000))
      await expect(request(1, 2)).resolves.toMatchObject({ provider: PREVIEW, model: 'fixture-fast' })
      expect(loadModels).toHaveBeenCalledTimes(1)

      await enter(2, 'detail '.repeat(1_000))
      await expect(request(2)).resolves.toMatchObject({ provider: PREVIEW, model: 'fixture-strong' })
      expect(loadModels).toHaveBeenCalledTimes(2)
      expect(append.mock.calls.map(call => call[1])).toEqual([
        expect.objectContaining({ turn: 1, model: 'fixture-fast', reason: 'short-text-turn' }),
        expect.objectContaining({ turn: 2, model: 'fixture-strong', reason: 'large-structured-turn' }),
      ])
    } finally {
      dispose()
      await ctx.fiber.dispose()
    }
  })

  it('replaces Core virtual-Auto switch guidance with the resolved real route', async () => {
    const ctx = new Context()
    const previous = { provider: PREVIEW, model: 'fixture-previous' }
    const append = vi.fn()
    const agent = { ctx, session: { append, requestHeader: () => ({ config: previous }) } } as unknown as Agent
    const scope = scopeTarget(agent, agent)
    ctx.provide('sessionProjections', {
      stateOf: () => ({ lastUsed: previous, pending: { provider: PREVIEW, model: AUTO } }),
    } as never)
    // Core installs this agent-scoped prepended listener during setup.
    ctx.on('agent/pre-step', async (_payload, next) => {
      const result = await next()
      if (result.kind === 'reject') return result
      return { ...result, messages: [...result.messages, createUserMessage({
        content: [{ type: 'text',
          text: '[model changed: assistant turns above this point were generated by fixture-previous; the session continues with auto]' }],
        source: { kind: 'model-selection', form: 'notice', summary: 'fixture-previous → auto' as never },
      })] }
    }, { prepend: true })
    const dispose = installAutoModelRouting(ctx, {
      async loadModels() { return [model('fixture-resolved', 128_000, 'medium')] },
    })
    ctx.emit(scope, 'agent/created', { agent })
    const signal = new AbortController().signal
    try {
      const input = [message('Continue.')]
      const result = await ctx.waterfall(scope, 'agent/pre-step',
        { agent, messages: input, turn: 1, step: 1, signal },
        async () => ({ kind: 'enter' as const, messages: input }))
      expect(result).toMatchObject({ kind: 'enter' })
      if (result.kind !== 'enter') throw new Error('expected enter')
      const text = result.messages.flatMap(item => item.content)
        .filter(block => block.type === 'text').map(block => block.text)
      expect(text).not.toContain(expect.stringContaining('continues with auto'))
      expect(text).toContain(
        '[model changed: assistant turns above this point were generated by fixture-previous; the session continues with fixture-resolved]',
      )
    } finally {
      dispose()
      await ctx.fiber.dispose()
    }
  })
})
