import { Context } from '@deepseek-ai/cordis'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { getBuiltinModels } from '@earendil-works/pi-ai/providers/all'

vi.mock('@earendil-works/pi-ai/providers/all', async (importOriginal) => {
  const original = await importOriginal<typeof import('@earendil-works/pi-ai/providers/all')>()
  return {
    ...original,
    getBuiltinModels(provider: Parameters<typeof original.getBuiltinModels>[0]) {
      const models = original.getBuiltinModels(provider)
      return provider === 'github-copilot'
        ? [...models.filter(model => model.id !== 'gpt-6-astra'), {
            ...models[0]!, id: 'gpt-6-astra', name: 'GPT-6 Astra', api: 'openai-responses' as const,
            reasoning: true, input: ['text', 'image'] as ('text' | 'image')[], contextWindow: 1_050_000, maxTokens: 128_000,
            thinkingLevelMap: { off: null, minimal: null, low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh', max: 'max' },
          }]
        : models
    },
  }
})

import { ROUTE_OWNERSHIP_EPOCH, type RouteMutation } from '../src/route-ownership.ts'
import { describeGitHubCopilotProviderProfile, inspectGitHubCopilotProviderProfile } from '../src/authorization-controller.ts'

// A recorded v2-era representation, not generated by today's preview code.
const LEGACY_HEADERS = {
  'User-Agent': 'GitHubCopilotChat/0.35.0',
  'Editor-Version': 'vscode/1.107.0',
  'Editor-Plugin-Version': 'copilot-chat/0.35.0',
  'Copilot-Integration-Id': 'vscode-chat',
}
const LEGACY_MODELS = [{
  id: 'gpt-6-astra', name: 'GPT-6 Astra', api: 'openai-responses',
  contextWindow: 1_050_000, maxTokens: 128_000, input: ['text', 'image'],
  reasoningEfforts: { off: null, low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh', max: 'max' },
}, { id: 'gpt-5.4', api: 'openai-responses' }]

function runtime(historical: boolean, availableModelIds: string[]) {
  const profile = historical ? {
    api: 'openai-responses', compat: { supportsStrictMode: false },
    headers: { 'X-Custom': 'preserved', ...LEGACY_HEADERS }, models: structuredClone(LEGACY_MODELS),
  } : undefined
  const settingsDocuments: Record<string, Record<string, unknown>> = {
    'llm-pi-ai': { providers: { unrelated: { preserved: true }, ...profile === undefined ? {} : { 'github-copilot': profile } } },
    'github-copilot': historical ? {
      temporaryRouteBackup: JSON.stringify({
        version: 2, phase: 'overlay', sourceRevision: 0, sourceEpoch: ROUTE_OWNERSHIP_EPOCH,
        providerExisted: true, preimage: { models: [{ id: 'claude-sonnet-4.5', api: 'anthropic-messages' }] }, postimage: { api: profile!.api, models: profile!.models },
        ownedHeaders: LEGACY_HEADERS,
      }),
    } : {},
  }
  const revisions: Record<string, number> = { 'llm-pi-ai': 1, 'github-copilot': 1 }
  const mutate = vi.fn(async (namespace: string, operations: readonly RouteMutation[], revision?: number) => {
    expect(revision).toBe(revisions[namespace])
    for (const operation of operations) {
      let target = settingsDocuments[namespace]!
      for (const segment of operation.path.slice(0, -1)) {
        target[segment] ??= {}
        target = target[segment] as Record<string, unknown>
      }
      const leaf = operation.path.at(-1)!
      if (operation.op === 'unset') delete target[leaf]
      else target[leaf] = structuredClone(operation.value)
    }
    revisions[namespace]!++
  })
  const ctx = new Context()
  const get = vi.fn((name: string) => {
    if (name === 'llmPiAiModelProtocol') throw new Error('unpublished Core service must not be consulted')
    if (name === 'credentials') return {
      readRecord: async () => ({ kind: 'grant', payload: {
        type: 'oauth', refresh: 'synthetic-refresh', access: 'synthetic-access',
        expires: 9_999_999_999_999, availableModelIds,
      } }),
    }
    if (name === 'settings') return {
      get: (namespace: string) => settingsDocuments[namespace], mutate,
      describe: () => Object.entries(settingsDocuments).map(([ns, user]) => ({ ns, user, revision: revisions[ns]! })),
    }
    return undefined
  })
  ctx.get = get as typeof ctx.get
  const fetch = vi.fn(async () => { throw new Error('no OAuth or network proof during journal restoration') })
  vi.stubGlobal('fetch', fetch)
  return { ctx, get, fetch, mutate, settingsDocuments, profile }
}

afterEach(() => { vi.clearAllMocks(); vi.unstubAllGlobals() })

describe('temporary GitHub Copilot model retirement', () => {
  it('restores the historical canonical route without transferring locally supported GPT-6 into Core', async () => {
    expect(getBuiltinModels('github-copilot').find(model => model.id === 'gpt-6-astra'))
      .toMatchObject({ api: 'openai-responses', reasoning: true })
    const harness = runtime(true, ['gpt-6-astra', 'gpt-5.4'])
    const before = structuredClone(harness.settingsDocuments)
    await expect(describeGitHubCopilotProviderProfile(harness.ctx)).resolves.toMatchObject({
      state: 'needs-repair',
    })
    expect(harness.settingsDocuments).toEqual(before)
    expect(harness.mutate).not.toHaveBeenCalled()
    await expect(inspectGitHubCopilotProviderProfile(harness.ctx)).resolves.toMatchObject({
      changed: true,
    })
    expect(harness.profile).toEqual({
      compat: { supportsStrictMode: false }, headers: { 'X-Custom': 'preserved' },
      models: [{ id: 'claude-sonnet-4.5', api: 'anthropic-messages' }],
    })
    expect(harness.settingsDocuments['llm-pi-ai']).toMatchObject({ providers: { unrelated: { preserved: true } } })
    expect(harness.settingsDocuments['github-copilot']).toEqual({})
    expect(harness.mutate).toHaveBeenCalledWith('github-copilot', [{ op: 'unset', path: ['temporaryRouteBackup'] }], 2)
    const markerWrites = harness.mutate.mock.calls.filter(([namespace, operations]) =>
      namespace === 'github-copilot' && operations[0]?.op === 'set')
    expect(markerWrites).toHaveLength(1)
    expect(JSON.parse((markerWrites[0]![1][0] as { value: string }).value).phase).toBe('restoring')
    harness.mutate.mockClear()
    await expect(inspectGitHubCopilotProviderProfile(harness.ctx)).resolves.toMatchObject({ changed: false })
    await expect(describeGitHubCopilotProviderProfile(harness.ctx)).resolves.toMatchObject({ state: 'ready' })
    expect(harness.mutate).not.toHaveBeenCalled()
    expect(harness.fetch).not.toHaveBeenCalled()
    expect(harness.get.mock.calls.some(([name]) => name === 'llmPiAiModelProtocol')).toBe(false)
  })

  it('refuses a preview-only historical preimage instead of restoring GPT-6 into canonical Core', async () => {
    for (const stage of ['overlay', 'restored-target']) {
      const harness = runtime(true, ['gpt-6-astra'])
      const journal = JSON.parse(harness.settingsDocuments['github-copilot']!.temporaryRouteBackup as string)
      journal.preimage.models = [{ id: 'gpt-6-astra', api: 'openai-completions' }]
      if (stage === 'restored-target') {
        journal.phase = 'restoring'
        journal.target = structuredClone(journal.preimage)
        journal.removeProfile = false
        const raw = harness.profile as Record<string, unknown>
        delete raw.api
        raw.models = structuredClone(journal.preimage.models)
        raw.headers = { 'X-Custom': 'preserved' }
      }
      harness.settingsDocuments['github-copilot']!.temporaryRouteBackup = JSON.stringify(journal)
      const before = structuredClone(harness.settingsDocuments)
      await expect(describeGitHubCopilotProviderProfile(harness.ctx)).resolves.toMatchObject({ state: 'conflict' })
      await expect(inspectGitHubCopilotProviderProfile(harness.ctx)).rejects.toMatchObject({ code: 'TEMPORARY_ROUTE_OWNERSHIP_CONFLICT' })
      expect(harness.settingsDocuments).toEqual(before)
      expect(harness.mutate).not.toHaveBeenCalled()
      expect(harness.fetch).not.toHaveBeenCalled()
    }
  })

  it('does not synthesize a canonical model list from locally supported GPT-6', async () => {
    const harness = runtime(false, ['gpt-6-astra'])
    await expect(inspectGitHubCopilotProviderProfile(harness.ctx)).resolves.toEqual({ changed: true })
    expect((harness.settingsDocuments['llm-pi-ai']!.providers as Record<string, unknown>)['github-copilot'])
      .toEqual({ compat: { supportsStrictMode: false } })
    expect(harness.settingsDocuments['github-copilot']).toEqual({})
    expect(harness.fetch).not.toHaveBeenCalled()
    expect(harness.get.mock.calls.some(([name]) => name === 'llmPiAiModelProtocol')).toBe(false)
  })
})
