import type { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { boundContextSummary, createUserMessage, LlmError } from '@deepseek-ai/dsh-llm'
import type { AccountModelDescriptor } from './account-model-catalog.ts'
import { AutoModelRoutingError, selectAutoModel } from './auto-model-routing.ts'
import type { AutoModelDecision } from './auto-model-routing.ts'
import { GITHUB_COPILOT_AUTO_MODEL_ID, GITHUB_COPILOT_PREVIEW_PROVIDER_ID } from './copilot-identity.ts'

declare module '@deepseek-ai/dsh-session/types' {
  interface SessionEventMap {
    'github-copilot/auto-model-decision': {
      turn: number
      step: number
      provider: typeof GITHUB_COPILOT_PREVIEW_PROVIDER_ID
      model: string
      taskClass: AutoModelDecision['taskClass']
      reason: AutoModelDecision['reason']
      candidateCount: number
    }
  }
}

export interface AutoModelHostDependencies {
  loadModels(signal: AbortSignal): Promise<readonly AccountModelDescriptor[]>
}

interface CapturedTurn {
  readonly turn: number
  readonly messages: readonly unknown[]
}

interface RoutedTurn {
  readonly turn: number
  readonly decision: AutoModelDecision
  recorded: boolean
}

function failure(code: string): LlmError {
  return new LlmError(code, 'INVALID_REQUEST')
}

async function decide(
  dependencies: AutoModelHostDependencies,
  signal: AbortSignal,
  messages: readonly unknown[],
): Promise<AutoModelDecision> {
  try { return selectAutoModel(await dependencies.loadModels(signal), messages) }
  catch (cause) {
    if (cause instanceof AutoModelRoutingError) throw failure(cause.code)
    throw cause
  }
}

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function autoIntent(ctx: Context, agent: Agent): boolean {
  const candidate: unknown = ctx.get('sessionProjections')
  if (!record(candidate) || typeof candidate.stateOf !== 'function') return false
  try {
    const state: unknown = candidate.stateOf(agent.session, 'modelSelection')
    if (!record(state) || !record(state.pending)) return false
    return state.pending.provider === GITHUB_COPILOT_PREVIEW_PROVIDER_ID
      && state.pending.model === GITHUB_COPILOT_AUTO_MODEL_ID
  } catch { return false }
}

function modelSelectionNotice(value: unknown): boolean {
  return record(value) && record(value.source) && value.source.kind === 'model-selection'
}

function routeLabel(provider: string, model: string, otherProvider: string): string {
  return provider === otherProvider ? model : `${provider}/${model}`
}

function actualNotice(agent: Agent, model: string) {
  const previous = agent.session.requestHeader()?.config
  if (previous === undefined || previous.provider === GITHUB_COPILOT_PREVIEW_PROVIDER_ID && previous.model === model) {
    return undefined
  }
  const from = routeLabel(previous.provider, previous.model, GITHUB_COPILOT_PREVIEW_PROVIDER_ID)
  const to = routeLabel(GITHUB_COPILOT_PREVIEW_PROVIDER_ID, model, previous.provider)
  return createUserMessage({
    content: [{
      type: 'text',
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: {
      kind: 'model-selection',
      form: 'notice',
      summary: boundContextSummary(`${from} → ${to}`),
    },
  })
}

/** Resolve virtual Auto once per Core turn before request/header persistence. */
export function installAutoModelRouting(ctx: Context, dependencies: AutoModelHostDependencies): () => void {
  const captured = new WeakMap<Agent, CapturedTurn>()
  const routed = new WeakMap<Agent, RoutedTurn>()
  const agentDisposers = new WeakMap<Agent, Dispose>()
  const activeDisposers = new Set<Dispose>()
  type Dispose = () => void
  const installAgent = (agent: Agent): void => {
    if (agentDisposers.has(agent)) return
    const dispose = agent.ctx.on('agent/pre-step', async ({ messages, turn, step, signal }, next) => {
      const result = await next()
      const entered = result.kind === 'enter' ? result.messages : messages
      captured.set(agent, { turn, messages: entered })
      if (result.kind !== 'enter' || signal.aborted || !autoIntent(ctx, agent)) return result
      let state = routed.get(agent)
      if (state?.turn !== turn) {
        state = {
          turn,
          decision: await decide(dependencies, signal, entered),
          recorded: false,
        }
        routed.set(agent, state)
      }
      const filtered = result.messages.filter(message => !modelSelectionNotice(message))
      const notice = actualNotice(agent, state.decision.model.id)
      return notice === undefined ? { ...result, messages: filtered }
        : { ...result, messages: [...filtered, notice] }
    }, { prepend: true })
    agentDisposers.set(agent, dispose)
    activeDisposers.add(dispose)
  }
  const removeCreated = ctx.on('agent/created', ({ agent }) => installAgent(agent))
  const removeDisposed = ctx.on('agent/disposed', ({ agent }) => {
    const dispose = agentDisposers.get(agent)
    dispose?.()
    if (dispose !== undefined) activeDisposers.delete(dispose)
    agentDisposers.delete(agent)
    captured.delete(agent)
    routed.delete(agent)
  })
  const removeRequest = ctx.on('agent/request', async ({ agent, turn, step, signal }, next) => {
    const resolved = await next()
    if (resolved.provider !== GITHUB_COPILOT_PREVIEW_PROVIDER_ID || resolved.model !== GITHUB_COPILOT_AUTO_MODEL_ID) {
      routed.delete(agent)
      return resolved
    }
    let state = routed.get(agent)
    if (state?.turn !== turn) {
      const input = captured.get(agent)
      if (input?.turn !== turn) throw failure('COPILOT_AUTO_TURN_CONTEXT_UNAVAILABLE')
      state = { turn, decision: await decide(dependencies, signal, input.messages), recorded: false }
      routed.set(agent, state)
    }
    if (!state.recorded) {
      agent.session.append('github-copilot/auto-model-decision', {
        turn,
        step,
        provider: GITHUB_COPILOT_PREVIEW_PROVIDER_ID,
        model: state.decision.model.id,
        taskClass: state.decision.taskClass,
        reason: state.decision.reason,
        candidateCount: state.decision.candidateCount,
      })
      state.recorded = true
    }
    return { ...resolved, model: state.decision.model.id }
  }, { prepend: true })
  return () => {
    removeCreated()
    removeDisposed()
    removeRequest()
    for (const dispose of activeDisposers) dispose()
    activeDisposers.clear()
  }
}
