import type { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { boundContextSummary, createUserMessage, LlmError } from '@deepseek-ai/dsh-llm'
import type { AccountModelDescriptor } from './account-model-catalog.ts'
import { AutoModelRoutingError, selectAutoModel } from './auto-model-routing.ts'
import type { AutoModelDecision } from './auto-model-routing.ts'
import { autoModelPreference, GITHUB_COPILOT_PREVIEW_PROVIDER_ID } from './copilot-identity.ts'
import type { AutoModelPreference } from './copilot-identity.ts'

export interface AutoModelHostDependencies {
  loadModels(signal: AbortSignal): Promise<readonly AccountModelDescriptor[]>
}

interface CapturedTurn {
  readonly turn: number
  readonly messages: readonly unknown[]
}

interface RoutedTurn {
  readonly turn: number
  readonly decision: AutoModelDecision
  recorded: boolean
}

function failure(code: string): LlmError {
  return new LlmError(code, 'INVALID_REQUEST')
}

async function decide(
  dependencies: AutoModelHostDependencies,
  signal: AbortSignal,
  messages: readonly unknown[],
  preference: AutoModelPreference,
): Promise<AutoModelDecision> {
  try { return selectAutoModel(await dependencies.loadModels(signal), messages, preference) }
  catch (cause) {
    if (cause instanceof AutoModelRoutingError) throw failure(cause.code)
    throw cause
  }
}

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function pendingAuto(ctx: Context, agent: Agent): string | undefined {
  const candidate: unknown = ctx.get('sessionProjections')
  if (!record(candidate) || typeof candidate.stateOf !== 'function') return undefined
  const state: unknown = candidate.stateOf(agent.session, 'modelSelection')
  if (!record(state) || !record(state.pending) || state.pending.provider !== GITHUB_COPILOT_PREVIEW_PROVIDER_ID) return undefined
  return typeof state.pending.model === 'string' && autoModelPreference(state.pending.model) !== undefined
    ? state.pending.model : undefined
}

function modelSelectionNotice(value: unknown): boolean {
  return record(value) && record(value.source) && value.source.kind === 'model-selection'
}

function routeLabel(provider: string, model: string, otherProvider: string): string {
  return provider === otherProvider ? model : `${provider}/${model}`
}

function actualNotice(agent: Agent, model: string) {
  const previous = agent.session.requestHeader()?.config
  if (previous === undefined || previous.provider === GITHUB_COPILOT_PREVIEW_PROVIDER_ID && previous.model === model) {
    return undefined
  }
  const from = routeLabel(previous.provider, previous.model, GITHUB_COPILOT_PREVIEW_PROVIDER_ID)
  const to = routeLabel(GITHUB_COPILOT_PREVIEW_PROVIDER_ID, model, previous.provider)
  return createUserMessage({
    content: [{
      type: 'text',
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: {
      kind: 'model-selection',
      form: 'notice',
      summary: boundContextSummary(`${from} → ${to}`),
    },
  })
}

/** Resolve virtual Auto once per Core turn before request/header persistence. */
export function installAutoModelRouting(ctx: Context, dependencies: AutoModelHostDependencies): () => void {
  type Dispose = () => void
  const captured = new WeakMap<Agent, CapturedTurn>()
  const routed = new WeakMap<Agent, RoutedTurn>()
  const agentDisposers = new WeakMap<Agent, Dispose>()
  const activeDisposers = new Set<Dispose>()
  const installAgent = (agent: Agent): void => {
    if (agentDisposers.has(agent)) return
    const removeAssembly = agent.ctx.on('system-prompt/assemble', async (_assembly, _context, next) => {
      const assembled = await next()
      const pending = pendingAuto(ctx, agent)
      if (pending === undefined) return assembled
      return { ...assembled, variables: {
        ...assembled.variables, provider: GITHUB_COPILOT_PREVIEW_PROVIDER_ID, model: pending,
      } }
    }, { prepend: true })
    const removePreStep = agent.ctx.on('agent/pre-step', async ({ messages, turn, signal }, next) => {
      const result = await next()
      const entered = result.kind === 'enter' ? result.messages : messages
      captured.set(agent, { turn, messages: entered })
      const pending = pendingAuto(ctx, agent)
      const preference = pending === undefined ? undefined : autoModelPreference(pending)
      if (result.kind !== 'enter' || signal.aborted || preference === undefined) return result
      let state = routed.get(agent)
      if (state?.turn !== turn) {
        state = {
          turn,
          decision: await decide(dependencies, signal, entered, preference),
          recorded: false,
        }
        routed.set(agent, state)
      }
      const filtered = result.messages.filter(message => !modelSelectionNotice(message))
      const notice = actualNotice(agent, state.decision.model.id)
      return notice === undefined ? { ...result, messages: filtered }
        : { ...result, messages: [...filtered, notice] }
    }, { prepend: true })
    const dispose = () => { removeAssembly(); removePreStep() }
    agentDisposers.set(agent, dispose)
    activeDisposers.add(dispose)
  }
  const removeCreated = ctx.on('agent/created', ({ agent }) => {
    installAgent(agent)
    return undefined
  })
  const removeDisposed = ctx.on('agent/disposed', ({ agent }) => {
    const dispose = agentDisposers.get(agent)
    dispose?.()
    if (dispose !== undefined) activeDisposers.delete(dispose)
    agentDisposers.delete(agent)
    captured.delete(agent)
    routed.delete(agent)
    return undefined
  })
  const removeRequest = ctx.on('agent/request', async ({ agent, turn, signal }, next) => {
    const resolved = await next()
    const pending = pendingAuto(ctx, agent)
    const virtualPreference = resolved.provider === GITHUB_COPILOT_PREVIEW_PROVIDER_ID
      ? autoModelPreference(resolved.model) : undefined
    const virtual = virtualPreference !== undefined
    if (!virtual && pending === undefined) {
      routed.delete(agent)
      return resolved
    }
    if (resolved.provider !== GITHUB_COPILOT_PREVIEW_PROVIDER_ID) {
      routed.delete(agent)
      return resolved
    }
    let state = routed.get(agent)
    if (state?.turn !== turn) {
      const input = captured.get(agent)
      if (input?.turn !== turn) throw failure('COPILOT_AUTO_TURN_CONTEXT_UNAVAILABLE')
      const preference = virtualPreference ?? (pending === undefined ? undefined : autoModelPreference(pending))
      if (preference === undefined) throw failure('COPILOT_AUTO_PREFERENCE_UNAVAILABLE')
      state = { turn, decision: await decide(dependencies, signal, input.messages, preference), recorded: false }
      routed.set(agent, state)
    }
    if (!state.recorded) {
      const projections: unknown = ctx.get('sessionProjections')
      if (virtual && record(projections) && typeof projections.stateOf === 'function') {
        const selection: unknown = projections.stateOf(agent.session, 'modelSelection')
        if (record(selection) && selection.pending === null && agent.session.requestHeader() === undefined) {
          Reflect.apply(agent.session.append, agent.session, ['model/selection', {
            provider: GITHUB_COPILOT_PREVIEW_PROVIDER_ID, model: resolved.model,
          }])
        }
      }
      // rc.2 append cannot mark plugin events ignorable; keep attribution out of the log.
      state.recorded = true
    }
    return { ...resolved, model: state.decision.model.id }
  }, { prepend: true })
  return () => {
    removeCreated()
    removeDisposed()
    removeRequest()
    for (const dispose of activeDisposers) dispose()
    activeDisposers.clear()
  }
}
